package com.sda.advanced.solution.zad17;

public enum ConversionType {
	METERS_TO_YARDS,
	YARDS_TO_METERS,
	CENTIMETERS_TO_INCHES,
	INCHES_TO_CENTIMETERS,
	KILOMETERS_TO_MILES,
	MILES_TO_KILOMETERS
}
